// Package qtinstaller provides utilities for building Qt Installer Framework packages.
package qtinstaller

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const installerLogo = "installerLogo"

// Config stores the properties to configure the installer.
type Config struct {
	DisplayName   string // Application display name
	Description   string // Application description
	Version       string // Software version
	ReleaseDate   string // Release date e.g 2022-12-12, default, current date
	PkgName       string // Globally unique identifier e.g com.domain.appname
	Executable    string // Path to the main Qt Executable generated by the build process.
	InstallerName string // Output installer name

	LicenceName string // Name of the licence for your software.
	LicencePath string // Path to the licence file. default licence.txt in the working dir
	Publisher   string // company publishing the software

	// Filename for a logo in PNG format used as QWizard::LogoPixmap.
	Logo string

	// Filename for a custom installer icon.
	//The actual file is looked up by attaching a '.icns' (macOS), '.ico' (Windows) suffix.
	//No functionality on Unix.
	InstallerApplicationIcon string
}

// Directories for a simple offline installer.
// Config, Data and Meta.
type installerDirs struct {
	Config string // config directory
	Data   string // packages/<pkg_name>/data
	Meta   string // packages/<pkg_name>/meta
}

// Default configuration.
// Sets the default version, date, installer name, licence name and
// licencePath.
var defaultConfig = Config{
	Version:       "0.1.0-1",
	ReleaseDate:   time.Now().Format("2006-01-02"),
	InstallerName: "Installer.exe",
	LicenceName:   "MIT License Agreement",
	LicencePath:   "licence.txt",
}

// Platform-specific example values for the generated .env template.
var platformDefaults = map[string]struct{ exePath, installerName, iconFile string }{
	"windows": {`C:\Qt\Projects\Releases\app.exe`, "Installer.exe", "favicon.ico"},
	"linux":   {"/path/to/release/app", "Installer", "favicon.png"},
	"darwin":  {"/path/to/release/app", "Installer", "favicon.png"},
}

// GenerateConfigFile writes the default .env file in the same directory.
func GenerateConfigFile() error {
	defaults, ok := platformDefaults[runtime.GOOS]
	if !ok {
		defaults = platformDefaults["linux"]
	}

	text := fmt.Sprintf(configTextTemplate,
		DisplayName,
		Publisher,
		Description,
		ReleaseDate,
		Version,
		PackageName,
		Executable, defaults.exePath,
		InstallerName, defaults.installerName,
		LicenceName,
		LicenceFile,
		Logo,
		InstallerApplicationIcon, defaults.iconFile,
	)
	return os.WriteFile(".env", []byte(text), 0640)
}

// GetInstallerDirs returns the expected default directories for the
// Qt installer framework (config, data, and meta).
func GetInstallerDirs(config *Config) *installerDirs {
	dirs := &installerDirs{
		Config: filepath.Join("./config"),
		Meta:   filepath.Join("./packages", config.PkgName, "meta"),
		Data:   filepath.Join("./packages", config.PkgName, "data"),
	}

	dirAbsPaths(dirs)
	return dirs
}

// Sets absolute paths for all dirs.
func dirAbsPaths(dirs *installerDirs) {
	configDir, _ := filepath.Abs(dirs.Config)
	dirs.Config = configDir

	MetaDir, _ := filepath.Abs(dirs.Meta)
	dirs.Meta = MetaDir

	DataDir, _ := filepath.Abs(dirs.Data)
	dirs.Data = DataDir
}

// WriteFiles generates data from config and dirs and writes it into the appropriate files.
func WriteFiles(config *Config, dirs *installerDirs) error {
	// Compute base names for files copied to config dir
	logoBase := filepath.Base(config.Logo)
	installLogoName := installerLogo + filepath.Ext(logoBase)

	installerIconBase := ""
	if config.InstallerApplicationIcon != "" {
		installerIconBase = filepath.Base(config.InstallerApplicationIcon)
	}

	// write config/config.xml
	err := os.WriteFile(
		filepath.Join(dirs.Config, "config.xml"),
		[]byte(fmt.Sprintf(configXMLTemplate,
			config.DisplayName, // Name
			config.Version,     // Version
			config.DisplayName, // Title
			config.Publisher,   // Publisher
			config.DisplayName, // StartMenuDir
			installLogoName,    // InstallerWindowIcon (base name in config dir)
			installerIconBase,  // InstallerApplicationIcon (base name in config dir)
			logoBase,           // Logo (base name in config dir)
			config.DisplayName, // TargetDir
		)),
		0640,
	)

	if err != nil {
		return err
	}

	// write config/controlscript.qs
	err = os.WriteFile(
		filepath.Join(dirs.Config, "controlscript.qs"),
		[]byte(controlScriptTmpl),
		0640,
	)
	if err != nil {
		return err
	}

	// copy config images described in the config.xml above
	err = copyFileToDir(config.Logo, dirs.Config)
	if err != nil {
		return err
	}

	// duplicate logo and save copy as installerlogo
	err = copyFileToDir(config.Logo, dirs.Config, installLogoName)
	if err != nil {
		return err
	}

	// copy application icon (if provided; optional on Linux)
	if config.InstallerApplicationIcon != "" {
		err = copyFileToDir(config.InstallerApplicationIcon, dirs.Config)
		if err != nil {
			return err
		}
	}

	// copy executable
	err = copyFileToDir(config.Executable, dirs.Data)
	if err != nil {
		return err
	}

	// On Linux, also copy logo to data dir for desktop entry icon
	if runtime.GOOS != "windows" {
		err = copyFileToDir(config.Logo, dirs.Data)
		if err != nil {
			return err
		}
	}

	// copy licence
	err = copyFileToDir(config.LicencePath, dirs.Meta)
	if err != nil {
		return err
	}

	// write package.xml
	err = os.WriteFile(
		filepath.Join(dirs.Meta, "package.xml"),
		fmt.Appendf(nil,
			packageXMLTemplate,
			config.DisplayName,
			config.Description,
			config.Version,
			config.ReleaseDate,
			config.LicenceName,
			filepath.Base(config.LicencePath),
		),
		0640,
	)

	if err != nil {
		return err
	}

	// Write the installscript.qs
	baseName := filepath.Base(config.Executable)
	linkName := strings.TrimSuffix(baseName, filepath.Ext(baseName)) + ".lnk"
	desktopFile := config.PkgName + ".desktop"

	return os.WriteFile(
		filepath.Join(dirs.Meta, "installscript.qs"),
		fmt.Appendf(nil,
			installScriptTmpl,
			baseName, linkName, baseName,
			baseName, linkName, baseName,
			desktopFile, baseName, logoBase, config.DisplayName,
		),
		0640,
	)
}

// copyFileToDir copies the srcFile to a dstDir directory.
// If the destination dir does not exit, it's created.
// If newName is provided(withthe file extension, it's used instead.)
func copyFileToDir(srcFile, dstDir string, newName ...string) error {
	_, file := filepath.Split(srcFile)

	err := os.MkdirAll(dstDir, 0755)
	if err != nil {
		return err
	}

	srcInfo, err := os.Stat(srcFile)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(srcFile)
	if err != nil {
		return err
	}

	// Use filepath.Join to create the destination path.
	dstPath := filepath.Join(dstDir, file)
	if len(newName) > 0 {
		dstPath = filepath.Join(dstDir, filepath.Base(newName[0]))
	}
	return os.WriteFile(dstPath, data, srcInfo.Mode().Perm())
}

// Reads key from environment variables.
// If the value returned is not empty, the param is updated.
// Otherwise it panics if this key was required.
func setConfigVar(param *string, key string, required bool) {
	value := os.Getenv(key)
	if value == "" {
		if required {
			log.Fatalf("evironment variable %s is required.\n", key)
		}
	} else {
		*param = value
	}
}

// NewConfig returns a new Config populated from environment variables.
func NewConfig() *Config {
	configCopy := defaultConfig
	config := &configCopy

	// Set platform-aware default installer name
	if runtime.GOOS != "windows" {
		config.InstallerName = "Installer"
	}

	// required env variables
	setConfigVar(&config.DisplayName, DisplayName, true)
	setConfigVar(&config.Description, Description, true)
	setConfigVar(&config.PkgName, PackageName, true)
	setConfigVar(&config.Executable, Executable, true)
	setConfigVar(&config.LicenceName, LicenceName, true)
	setConfigVar(&config.LicencePath, LicenceFile, true)
	setConfigVar(&config.Publisher, Publisher, true)
	setConfigVar(&config.Logo, Logo, true)

	// InstallerApplicationIcon is required on Windows, optional on Linux
	if runtime.GOOS == "windows" {
		setConfigVar(&config.InstallerApplicationIcon, InstallerApplicationIcon, true)
	} else {
		setConfigVar(&config.InstallerApplicationIcon, InstallerApplicationIcon, false)
	}

	// Optional env variables
	setConfigVar(&config.ReleaseDate, ReleaseDate, false)
	setConfigVar(&config.Version, Version, false)
	setConfigVar(&config.InstallerName, InstallerName, false)
	return config
}

// CreateDirectoryStructure creates the config, data, and meta directories.
// Old directories are deleted if they exist.
func CreateDirectoryStructure(dirs *installerDirs) error {
	// Remove old directories.
	os.RemoveAll(dirs.Config)
	os.RemoveAll(dirs.Meta)
	os.RemoveAll(dirs.Data)

	// Create new directories.
	if err := os.MkdirAll(dirs.Config, 0755); err != nil {
		return err
	}

	if err := os.MkdirAll(dirs.Meta, 0755); err != nil {
		return err
	}
	return os.MkdirAll(dirs.Data, 0755)
}

func panicIfNotFileExists(path ...string) {
	for _, f := range path {
		if _, err := os.Stat(f); err != nil {
			log.Fatalf("File not found: %s\n", f)
		}
	}
}

func AssertFilesExist(config *Config) {
	required := []string{
		config.Executable,
		config.LicencePath,
		config.Logo,
	}
	if config.InstallerApplicationIcon != "" {
		required = append(required, config.InstallerApplicationIcon)
	}
	panicIfNotFileExists(required...)
}

// GetQtBinaries locates the deploy tool and binarycreator.
// If the deploy tool is not found, deployTool is empty and the caller
// should fall back to DeployQtLibs on Linux.
func GetQtBinaries() (deployTool string, binaryCreator string, err error) {
	if runtime.GOOS == "windows" {
		deployTool, err = exec.LookPath("windeployqt.exe")
		if err != nil {
			log.Println("windeployqt.exe not in PATH, searching common Qt installation paths...")
			deployTool, err = findWinDeployQt()
			if err != nil {
				return "", "", err
			}
		}

		binaryCreator, err = exec.LookPath("binarycreator.exe")
		if err != nil {
			return "", "", fmt.Errorf("binarycreator.exe is not installed or not in PATH. Install the Qt Installer Framework and try again")
		}
	} else {
		// Try external tools first: linuxdeployqt, cqtdeployer
		deployTool, _ = exec.LookPath("linuxdeployqt")
		if deployTool == "" {
			deployTool, _ = exec.LookPath("cqtdeployer")
		}
		if deployTool == "" {
			log.Println("No external deploy tool found, will use built-in Qt library deployer")
		}

		binaryCreator, err = exec.LookPath("binarycreator")
		if err != nil {
			return "", "", fmt.Errorf("binarycreator is not installed or not in PATH. Install the Qt Installer Framework and try again")
		}
	}

	return deployTool, binaryCreator, nil
}
